/* generated by Makefile */
#define SCM_PKGDATA_DIR "@PREFIX@/share/guile"
#define SCM_LIBRARY_DIR "@PREFIX@/share/guile/@guile_VERSION_MAJOR@.@guile_VERSION_MINOR@"
#define SCM_SITE_DIR    "@PREFIX@/share/guile/site"
#define SCM_BUILD_INFO { \
{ "srcdir",            "@CMAKE_SOURCE_DIR@/libguile" }, \
{ "top_srcdir",        "@CMAKE_SOURCE_DIR@" }, \
{ "prefix",	           "@PREFIX@" }, \
{ "exec_prefix",       "@PREFIX@" }, \
{ "bindir",	           "@PREFIX@/bin" }, \
{ "sbindir",	       "@PREFIX@/sbin" }, \
{ "libexecdir",	       "@PREFIX@/libexec" }, \
{ "datadir",	       "@PREFIX@/share" }, \
{ "sysconfdir",	       "@PREFIX@/etc" }, \
{ "sharedstatedir",    "@PREFIX@/com" }, \
{ "localstatedir",     "@PREFIX@/var" }, \
{ "libdir",	           "@PREFIX@/lib" }, \
{ "infodir",	       "@PREFIX@/share/info" }, \
{ "mandir",	           "@PREFIX@/share/man" }, \
{ "includedir",	       "@PREFIX@/include" }, \
{ "pkgdatadir",	       "@PREFIX@/share/guile" }, \
{ "pkglibdir",	       "@PREFIX@/lib/guile" }, \
{ "pkgincludedir",     "@PREFIX@/include/guile" }, \
{ "guileversion",      "@guile_VERSION@" }, \
{ "libguileinterface", "21:0:4" }, \
{ "LIBS",	           "  -lgmp -lcrypt -lm -lltdl " }, \
{ "CFLAGS",	           " -pthread" }, \
{ "buildstamp",        "@BUILDSTAMP@" }, \
}
